name: "cleanup-folder-action"
description: "cleanup-folder-action"

runs:
  using: "composite"
  steps:
    - name: Cleanup build folder
      shell: bash
      run: |
        rm -rf ./* || true
        rm -rf ./.??* || true

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "message-square"
  color: "gray-dark"
