name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  e2e-default:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Run
        id: test-run
        uses: ./

      - name: Check repo after action
        id: post-action
        run: echo "result="$(ls -a)"" >> $GITHUB_OUTPUT

      - name: Assert placeholder
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.post-action.outputs.result }}
          expected: ". .."

  e2e:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - e2e-default

    steps:
      - name: Collect Results
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ toJson(needs) }}
          skip_allowed: false
